### ISSUE TITLE
Cannot install the module

### ISSUE THREAD

**Issue by dcoughler** [SvenWerlen/moulinette-imagesearch#4]
Foundry Version 10 - Build 291

Every time I try to install the module, I get the following error:

```
setup.js:292 Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/svenwerlen/moulinette-imagesearch/master/module.json"
The requested manifest at "https://raw.githubusercontent.com/svenwerlen/moulinette-imagesearch/master/module.json" did not provide module manifest data.
    at Module.installPackage (file:///home/ubuntu/foundry/resources/app/dist/packages/views.mjs:1:1634)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///home/ubuntu/foundry/resources/app/dist/server/views/setup.mjs:1:1980)
```

Hosting on Oracle Cloud.

**Comment by SvenWerlen** [comment]
Sorry for my late answer. It might have been one specific version which didn't have a working JSON file.
I wasn't able to clearly identify the issue but since nobody reported this issue, I assume that it's fixed.
